### ISSUE TITLE
Gatsby Plugin

### ISSUE THREAD

**Issue by jaredpalmer** [jsxstyle/jsxstyle#105]
Would be really nice for static marketing sites

**Comment by meyer** [comment]
ooh, good idea. I’ll look into it!

**Comment by meyer** [comment]
I did some preliminary investigation and it looks like this should be pretty straightforward. I’m currently stuck on a webpack 1 (!!!!?!?!?!?!?) issue related to `jsxstyle-loader`’s virtual filesystem. When I get a sec I’ll keep digging to figure out what’s going on.

Couple things that don’t seem to be written down anywhere that I need to know:
1. In what order are loaders applied? Config order?
2. How does Gatsby deal with plugin conflicts? I’d like to add SSR style inlining using `replaceRenderer` but I don’t know how to deal with another `replaceRenderer` call. For now I’m assuming that the last one wins.

Related: holy shit, Gatsby still uses webpack 1. I’m speechless.

**Comment by lettertwo** [comment]
This is a great idea! You may want to consider targeting the [v2](https://github.com/gatsbyjs/gatsby/tree/v2) branch (currently in alpha). It uses Webpack 4, and includes various API changes for plugins that you may want to adopt now.

**Comment by meyer** [comment]
@lettertwo oh cool, I’ll take a look. Thanks!

**Comment by jaredpalmer** [comment]
I DM’d Kyle about Gatsby plugins in regards to my Razzle project (I’m working on a similar system). They run top to bottom, but should try to be written in a way that is independent of ordering.

**Comment by meyer** [comment]
@jaredpalmer dope, thanks!

**Comment by aamorozov** [comment]
@meyer 
The current implementation is not extracting the styles correctly on initial page load when serving the site from production files. I've created a repo to reproduce - https://github.com/aamorozov/gatsby-jsxstyle-issue. 
I've also tried updating https://github.com/jsxstyle/jsxstyle/blob/master/packages/gatsby-plugin-jsxstyle/gatsby-ssr.js#L11 to `exports.replaceRenderer = ({ setHeadComponents }) => {` but it didn't do the trick. Not sure if you're actively working on this, but thought to share

**Comment by meyer** [comment]
hi @aamorozov! Let’s continue the discussion in #122.
