### ISSUE TITLE
Runtime autoprefix?

### ISSUE THREAD

**Issue by jaredpalmer** [jsxstyle/jsxstyle#106]
Wondering if there is a way to make autoprefixing easier on users so jsxstyle works out of the box with CRA in every browser. 

Can we use this in a way that works by default but then turns off if the loader is present somehow???

https://github.com/rofrischmann/inline-style-prefixer

I know Glamor, RN Web, and SC use it.

**Comment by meyer** [comment]
I’ve shied away from `inline-style-prefixer` in the past as it does quite a bit more than we need, but for the [browsers we say we support](https://github.com/smyte/jsxstyle/blob/423531c/README.md#browser-support), we should definitely do something.

If it’s just style prop _names_ that need autoprefixing, we could do something pretty naive. if it’s prop _values_ as well, we’d need something more robust and I’d probably give `inline-style-prefixer` another look. I need to do some digging to get an idea of what props need to be autoprefixed these days.

Back in the 1.0 days, we had an (undocumented) injectable autoprefixer. I could look into adding that feature back.

As I’m typing this I seem to remember discussing this IRL a while ago. Flexbox properties were the main issue, right? What range of browsers are you looking to support?

**Comment by jaredpalmer** [comment]
Yeah flex is the killer one. Honestly I don’t even know what to prefix since I’m so used to autoprefixer taking care of it 😂
