### ISSUE TITLE
RFC: Default media query set

### ISSUE THREAD

**Issue by meyer** [jsxstyle/jsxstyle#116]
In the spirit of zero configuration™®, jsxstyle could provide a few preset media query prefixes based on a sensible set of breakpoints. The user would still be able to specify breakpoints in the `mediaQueries` prop, but this would (hopefully) be the exception rather than the rule.

Ideally the user would be able to globally override this default media query set as well. This would likely be an injected option (similar to `cache.injectOptions`), since a media query provider component makes static analysis impossible across multiple files.

@chenxsan lmk if you have thoughts on this.

**Comment by chenxsan** [comment]
I think a default preset media queries is enough for most, but of course users should be able to override it somewhere globally if they need a total different set. In some cases, we might want make a little change to some special components, then `mediaQueries` defined on components should be merged with the default one, just like `Object.assign(default, mediaQueries)`.

Right now I have three media queries in my blog theme https://github.com/OkMarvin/january/blob/master/src/constants.js#L1-L5:

```js
module.exports.bps = {
  sm: 'screen and (min-width: 45em)',
  lg: 'screen and (min-width: 65em)',
  xlg: 'screen and (min-width: 81em)'
}
```
But it took me a lot time to figure them out. I think a default one would be helpful.

**Comment by chenxsan** [comment]
First time I defined those media queries in my constants module, I write ES6 syntax, then I found I have to specify `whitelistedModules` https://github.com/smyte/jsxstyle/tree/master/packages/jsxstyle-loader#whitelistedmodules:

```
{
      loader: 'jsxstyle-loader',
      options: {
        whitelistedModules: [require.resolve('./src/constants')]
      }
    }
```
So either I use CommonJS syntax in my constants module or I use `webpack.config.babel.js`, the later is complex, then I just change my constants module from ES6 syntax to CommonJS.

I think a default media queries set would make my change unnecessary?

**Comment by meyer** [comment]
I’m considering taking media queries in a different direction, so I’m going to close this for now.

More context here: https://github.com/jsxstyle/jsxstyle/issues/90#issuecomment-606915879
