### ISSUE TITLE
Modules specified in whitelistedModules do not get compiled with webpack

### ISSUE THREAD

**Issue by meyer** [jsxstyle/jsxstyle#117]
At the moment, modules specified in `jsxstyle-loader`’s `whitelistedModules` config option are not parsed by webpack, which means that they need to be written in node-friendly javascript. This is unexpected and can be confusing (see https://github.com/smyte/jsxstyle/issues/116#issuecomment-386930000). It also kinda sucks for folks who use TypeScript, since the modules have to be written in plain JS and will therefore be untyped. It should be possible (and fairly straightforward) to compile `whitelistedModules` with a child compiler.

**Comment by chenxsan** [comment]
@meyer Hi, I'm trying to make it work in my project by modifying the js file here https://github.com/jsxstyle/jsxstyle/blob/master/packages/jsxstyle-webpack-plugin/src/utils/ast/getStaticBindingsForScope.ts#L65:

```
if (whitelist.indexOf(moduleName) > -1) {
        const compiler = webpack({
          entry: moduleName,
          output: {
            path: '/',
            filename: path.basename(moduleName),
            libraryTarget: 'commonjs'
          }
        })
        compiler.outputFileSystem = fs
        compiler.run(function(err, stats) {
          fs.readFile(
            path.join('/', path.basename(moduleName)),
            'utf-8',
            function(err, str) {
              const src = requireFromString(str, moduleName)
              if (sourceModule.destructured) {
                if (sourceModule.imported) {
                  ret[k] = src[sourceModule.imported]
                }
              } else {
                // crude esmodule check
                // TODO: make sure this actually works
                if (src && src.__esModule) {
                  ret[k] = src.default
                } else {
                  ret[k] = src
                }
              }
            }
          )
        })
      }
```
As far as I see my es6 module in `whitelistedModules` did get compiled into commonjs code, but there's still warning from `loader.js`:

> Module Warning (from ./node_modules/jsxstyle-webpack-plugin/lib/loader.js):
    cannot evaluate media query prop: `bps`

Am I missing something here? Or am I totally wrong modifying `getStaticBindingsForScope` file? Would love to get some suggest here :)

**Comment by meyer** [comment]
Hey, thanks for tackling this! I think you’re in the right neighbourhood, but I think if you want to compile whitelisted modules using webpack, a *child compiler* might be a better way to go. The main difference is that you would be calling webpack *in* webpack as a part of the build process instead of outside of webpack.

The general idea:

- webpack starts up.
- before each compilation, child compilers compile each entry in `whitelistedModules` and use the node `module` module to simulate a `require`.
- the object of transpiled modules keyed by module path name is passed to `extractStyles`.

This article is a pretty good summary of how to use webpack’s child compiler functionality: https://medium.com/@prateekbh/my-experience-writing-a-webpacks-child-compiler-plugin-a1237c175947

I originally wanted to use the source webpack config to compile whitelisted modules, but the more I think about it, the more I think that a very permissive babel config would cover just about every use case.

**Comment by chenxsan** [comment]
@meyer I read that article but I'm afraid our case is a little different from that one. In our case we want to finish child compiler as soon as possible so modules in `whitelistedModules` would get transpiled before loaders applied, but I don't know how to make it.

Here's what I got so far:

```typescript
const compileWhitelistedModulesPlugin = (compilation, callback): void => {
      // first we save whitelistedModules option to this.whitelistedModules
      const { rules } = new RuleSet(
        (compiler.options.module && compiler.options.module.rules) || []
      );
      for (const rule of rules) {
        for (const use of rule.use) {
          if (use.loader.includes('jsxstyle-webpack-plugin')) {
            this.whitelistedModules = use.options.whitelistedModules;
            break;
          }
        }
      }
      // create childCompiler
      const childCompiler = compilation.createChildCompiler(this.pluginName, {
        ...compiler.options.output,
        filename: '[name]', // do not apply hash
      });
      childCompiler.context = compiler.context;
      // add entry
      this.whitelistedModules.forEach(entry => {
        new SingleEntryPlugin(childCompiler.context, entry, entry).apply(
          childCompiler
        );
      });
      // run
      childCompiler.runAsChild((err, entries, childCompilation) => {
        if (!err) {
          this.whitelistedModules.forEach(mod => {
            // save transpiled module to this.ctx.compiledWhitelistedModules
            this.ctx.compiledWhitelistedModules[mod] = childCompilation.assets[
              mod
            ].source();
          });
          callback();
        } else {
          callback(err);
        }
      });
    };
// some other code ......
compiler.hooks.make.tapAsync(
        this.pluginName,
        compileWhitelistedModulesPlugin
      );
```
It won't work because there're cases where loader runs before we get whitelistedModules transpiled.

**Comment by meyer** [comment]
@chenxsan if you push your WIP code up to github we can iterate on it on a branch rather than in the comments. Can you submit what you have so far as a pull request?

**Comment by chenxsan** [comment]
@meyer Of course, it would be much easier to talk with code :)

**Comment by meyer** [comment]
at long last i am taking a crack at this issue…

**Comment by meyer** [comment]
at long last i am again taking a crack at this issue… 😅
