### ISSUE TITLE
jsxstyle’s `InlineFlex` component is deprecated and will be removed in future versions of jsxstyle.

### ISSUE THREAD

**Issue by chenxsan** [jsxstyle/jsxstyle#121]
I just saw this warning in my console. It's alright, I'll consider updating it later with [whatever works](https://github.com/jsxstyle/jsxstyle/issues/9#issuecomment-260856490).

But then I found that `jsxstyle-webpack-plugin` won't extract the styles:

```jsx
<InlineFlex
      props={{ to: '/' }}
      component={Link}
      alignItems='center'
      color='#4a4a4a'
      fontSize='1.618em'
      lineHeight='2.625em'
      textDecoration='none'
      linkColor='#4a4a4a'
    >
      {props.logo && (
        <Inline
          component='img'
          maxWidth={42}
          border='none'
          marginRight={10}
          props={{ src: props.logo, alt: props.siteTitle }}
        />
      )}
      {props.siteTitle}
    </InlineFlex>
```

<img width="690" alt="image" src="https://user-images.githubusercontent.com/1091472/41885575-25cec1e8-792b-11e8-859c-99dcca2dcb66.png">

It would be great if `jsxstyle-webpack-plugin` still work with `InlineFlex` until `InlineFlex` get removed.

**Comment by meyer** [comment]
Ah yeah, that is to be expected. `InlineFlex` and a few other components have been deprecated as of jsxstyle 2.0, and `jsxstyle-webpack-plugin` was built right after the deprecation. Support for deprecated components was intentionally omitted.

I’ve been meaning to add `InlineRow` and `InlineCol` components; I’ll add those now.
