### ISSUE TITLE
Gatsby plugin not extacting styles correctly on initial page load

### ISSUE THREAD

**Issue by meyer** [jsxstyle/jsxstyle#122]
> The current implementation is not extracting the styles correctly on initial page load when serving the site from production files. I've created a repo to reproduce - https://github.com/aamorozov/gatsby-jsxstyle-issue. 
> Not sure if you're actively working on this, but thought to share - i'll keep digging and add a pr if i figure out why it's not working correctly.

_Originally posted by @aamorozov in https://github.com/jsxstyle/jsxstyle/issues/105#issuecomment-433432957_

---

> It looks like it is not rendering the styles that are set directly to jsx element, i.e. `Row/Column/etc` on `gatsby serve`, however, it is working correctly when developing locally.

_Originally posted by @aamorozov in https://github.com/jsxstyle/jsxstyle/issues/105#issuecomment-433465107_

**Comment by meyer** [comment]
@aamorozov thanks for the bug report and the repro! I’ve cloned the repro repo and have run `yarn build` and `yarn serve` and, as you mentioned, things seem to be working as expected locally.

What issue are you seeing specifically? Is it related to the `Dropdown` component that has the runtime CSS classname as well as the extracted classname?

> <img width="500" alt="screenshot 2018-10-26 11 24 21" src="https://user-images.githubusercontent.com/13781/47585306-be966980-d911-11e8-8164-27177842fea6.png">

**Comment by aamorozov** [comment]
I just found a fix for the issue. It worked for the repro repo and for my actual project. Will add a pr shortly @meyer

**Comment by meyer** [comment]
@aamorozov nice, sounds good!

**Comment by aamorozov** [comment]
Added pr in https://github.com/jsxstyle/jsxstyle/pull/123, it solved the issue for me. I also saw you commented on my issue in gatsby repo, so not sure if you've done more digging into that - my update might not be as diverse as it should be, but again, it solves the issue for me for a mid level code base.
