### ISSUE TITLE
Pass className to custom element component with different prop name

### ISSUE THREAD

**Issue by L42y** [jsxstyle/jsxstyle#124]
with following code
```jsx
<Box props={{src: 'https://'}} objectFit="cover" component="amp-img" />
```
result code markup would be:
```html
<amp-img src="" className="_fct69z">
```
but <amp-img> is a custom element and only recognize class attribute, how should we solve this issue?

**Comment by L42y** [comment]
I guess we need to detect if an element is a custom element and pass `className` as `class` instead?

**Comment by meyer** [comment]
@L42y hmmm, I’d like to avoid custom element detection if at all possible. I would be open to a very simple, very naive custom element check though (for example, the presence of a dash in the `component` prop value).

Would it be worth creating a `jsxstyle-amp` or `jsxstyle/amp` package?

**Comment by L42y** [comment]
@meyer thank your for your input, right now I just create a separate component:

```jsx
class AMPJsxstyle extends Component {
  static propTypes = {
    props: PropTypes.object,
    style: PropTypes.object,
    children: PropTypes.any,
    className: PropTypes.string.isRequired,
    component: PropTypes.string.isRequired
  };

  static defaultProps = {
    component: 'amp-layout'
  };

  render() {
    const {props, style, children, component: Comp} = this.props;

    return (
      <Comp
        {...props}
        class={cache.getClassName(this.props, this.props.className)}
        style={style}>
        {children}
      </Comp>
    );
  }
}
```

maybe I could expand it to an separate package as you said

**Comment by meyer** [comment]
@L42y ha, that’s perfect! Exactly how I hoped the exported style cache would be used.

**Comment by L42y** [comment]
I'm going to close this issue since it's solvable by a separate component.
