### ISSUE TITLE
Imported media query object is not accepted by mediaQueries prop 

### ISSUE THREAD

**Issue by aamorozov** [jsxstyle/jsxstyle#125]
#### Steps to reproduce
1. Pull down the repo 
https://github.com/aamorozov/gatsby-jsxstyle-issue
2. Run `yarn && gatsby develop`
3. Open index page 
4. Resize the browser 
#### Expected behavior 
Both Image grid and copy section above should turn into a column below 640px vp width
#### Actual behavior 
Only the image grid transforms into a column. 
Reference how the mediaQueries are set for image grid: 
https://github.com/aamorozov/gatsby-jsxstyle-issue/blob/master/src/components/imageGrid.js#L8-L11

Reference how the mediaQueries are set for copy section: 
https://github.com/aamorozov/gatsby-jsxstyle-issue/blob/master/src/pages/index.js#L9

**Comment by aamorozov** [comment]
It looks like it is not applying the media query prefix correctly and just adds it as a prefix to the prop:

 
![screen shot 2018-11-07 at 8 30 31 pm](https://user-images.githubusercontent.com/10227658/48171956-003cf200-e2cc-11e8-9952-536fb461b88d.png)

**Comment by meyer** [comment]
@aamorozov yeah, the `mediaQueries` prop is being stripped out if it can be evaluated, regardless of whether or not it’s in use. I need to add special cases for the following:

- spread present (one of the spread props might be `mediaQueries` or a mq-prefixed prop)
- non-static `mediaQueries` prop present

**Comment by meyer** [comment]
This poor bug has gone unfixed for so long, sorry 😩

I’m working on the roadmap for v3 at the moment and the media query API will be changing  (details here: https://github.com/jsxstyle/jsxstyle/issues/90#issuecomment-606915879). Due to this change I’m going to close this issue as wontfix.
