### ISSUE TITLE
React 15 and `componentWillMount`

### ISSUE THREAD

**Issue by artnez** [jsxstyle/jsxstyle#131]
Using `jsxstyle` with React 15 has an unexpected behavior due to this line:
https://github.com/jsxstyle/jsxstyle/blob/master/packages/jsxstyle/src/jsxstyle.tsx#L129

Using `componentDidMount` instead of `componentWillMount` causes the first render pass to *always* have an empty class name. This makes it impossible for parent components to do any DOM calculations on their own `componentDidMount()` lifecycle methods.

Another side effect is that every component is always rendered twice (first time without a class name, second time due to `setState()` on `componentDidMount()`).

**Comment by artnez** [comment]
Thanks for the quick fix! When will the new version be out? Deciding if I should roll out a forked build today in the interim.

**Comment by meyer** [comment]
@artnez sorry for the delay, I had some yarn/npm weirdness on my end. I just published this as `jsxstyle@2.1.5`! Thanks again for the bug report 🙏
