### ISSUE TITLE
Break with using thread-loader on production

### ISSUE THREAD

**Issue by Sunshine168** [jsxstyle/jsxstyle#133]
Hi, here is my problem

version:
```
"jsxstyle-webpack-plugin": "^1.1.3",
"jsxstyle": "^2.1.3",
```

error:
```
 Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
    Thread Loader (Worker 0)
    jsxstyle-webpack-plugin must be added to the plugins array in your webpack config
```

loader:
```
    use: [
      'thread-loader',
      {
        loader: 'babel-loader',
        options: {
          cacheDirectory: true
        }
      }
    ]
```
after remove 'thread-loader' , it work well

**Comment by meyer** [comment]
@Sunshine168 hmm, that’s interesting. Investigating…

**Comment by meyer** [comment]
Looks like `thread-loader` [two major limitations](https://webpack.js.org/loaders/thread-loader/#usage) that make compatibility with `jsxstyle-webpack-plugin` a bit challenging:

> - Loaders cannot emit files.
> - Loaders cannot use custom loader API (i. e. by plugins).

`jsxstyle-webpack-plugin` is first and foremost a plugin, which means that the companion loader cannot be used without the context object that the plugin provides to each loader instance. In addition, the loader emits a CSS file for each JS file that it runs on as well.

It should theoretically be possible to have a loader-only version of `jsxstyle-webpack-plugin`, but this is not something I’d be able to achieve in the near future. If you’re looking to reduced build/rebuild times, `jsxstyle-webpack-plugin`’s companion loader works quite well with `cache-loader`.

Sorry I couldn’t give you better news. Do let me know if you have any additional questions.
