### ISSUE TITLE
Replace most of the AST traversal in `extractStyles` with the TypeScript type checker

### ISSUE THREAD

**Issue by petehunt** [jsxstyle/jsxstyle#136]
Today we traverse the AST to extract out static styles with a bunch of AST traversal heuristics. We could replace a lot of them with the TypeScript typechecker, which can infer literal types from the expressions passed into `jsxstyle` props.

**Comment by meyer** [comment]
I am suuuuper into this idea as long as we can continue to support non-TS folks.

**Comment by meyer** [comment]
Closing for now.
