### ISSUE TITLE
TS2503: Cannot find namespace 'JSX'. 

### ISSUE THREAD

**Issue by peltomaa** [jsxstyle/jsxstyle#138]
`./node_modules/jsxstyle/preact/lib/jsxstyle-preact.d.ts:32:11` throws `TS2503: Cannot find namespace 'JSX'` error when using Preact 10.0.1 with Typescript.

Seems to be similar error to https://github.com/preactjs/preact-router/issues/316

**Comment by meyer** [comment]
It looks like the global `JSX` namespace has moved to `preact.JSX`. Should have a fix out shortly. Sorry for the delay!
