### ISSUE TITLE
React Native (react-native-web)

### ISSUE THREAD

**Issue by natew** [jsxstyle/jsxstyle#143]
Looking at forking this library (again, I've used parts of the babel plugin for other UI kits) to support the setup we have for a React Native / rnw app.

Basically would limit the props to the react-native ones, still allow for media queries when used for the web. We have a few views we use that are inspired by SwiftUI (VStack, HStack, ZStack) so I'd probably modify a bit more.

I assume they will diverge too much to be able to keep them in this repo, but if anyone has ideas or feels it could be made compatible I'd be happy to try.

**Comment by meyer** [comment]
@natew I’ve wanted to add React Native Web support for a while now but haven’t yet had a project that uses RNW. How would you envision it working? Would it completely bypass the StyleSheet API?

**Comment by natew** [comment]
Finally got around to splitting it out into it's own repo and publishing: https://github.com/natew/snackui

It's not really well documented yet but should work, uses a forked version of the JSXUI compiler. We really enjoy using it for a fairly large app, just needs media queries and some theme support.

**Comment by nandorojo** [comment]
@natew very cool. Excited to try it out.
