### ISSUE TITLE
React native web support

### ISSUE THREAD

**Issue by nandorojo** [jsxstyle/jsxstyle#152]
Hey there, I'm hoping to use the webpack plugin for react native web components & inline styles. Any idea how I could do that? Could it extract component styles somehow?

I'm a complete novice when it comes to webpack, but I maintain [Dripsy](https://github.com/nandorojo/dripsy), a react native (web) design system, and am looking for a way to integrate this for improved web performance.

**Comment by meyer** [comment]
hey @nandorojo! issue #143 might be of interest to you. @natew forked `jsxstyle-webpack-plugin` and bent it to his will for his own RNW library.

You should be fine without a ton of webpack know-how, but I’d recommend getting very familiar with javascript ASTs so you can modify the plugin to suit your needs. It’s a bit challenging but mainly just _extremely verbose_. I lean pretty heavily on [astexplorer.net](https://astexplorer.net/) for any sort of AST work like this. It’s a fantastic tool. The TypeScript types for babel are fantastic as well. If you use the type predicate functions they provide (`isNullLiteral` and friends), you get proper type narrowing. I use them all over the place in `jsxstyle-webpack-plugin`.

**Comment by nandorojo** [comment]
Got it, good to know. I really appreciate the thoughtful pointers, I'll look into all of this. Webpack is perhaps the first territory I time it basically impossible to learn by reading code, so I'll use those resources. Hopefully I can make it happen. Much appreciated.

**Comment by meyer** [comment]
sure thing! I’m going to close this issue but feel free to post updates/questions here; I’d love to see how it’s going for you!
