### ISSUE TITLE
Compatibility with Typescript@5.1.6

### ISSUE THREAD

**Issue by appsforartists** [jsxstyle/jsxstyle#188]
### What’s happening?

Cannot upgrade my project to `typescript@5.1.6` from `4.6.4`.  This is the build error, which appears to be internal to `jsxstyle`:

```
../../../node_modules/jsxstyle/preact/lib/index.d.ts:43:28 - error TS2344: Type 'ComponentProps' does not satisfy the constraint 'StylableComponentProps'.

43   component?: AnyComponent<ComponentProps>;
                              ~~~~~~~~~~~~~~

  ../../../node_modules/jsxstyle/preact/lib/index.d.ts:38:32
    38 export interface JsxstyleProps<ComponentProps>
                                      ~~~~~~~~~~~~~~
    This type parameter might need an `extends StylableComponentProps` constraint.
```

### What should be happening instead?

Build should succeed.

### Which package is causing this issue?

jsxstyle, typescript

### Additional context

I tried updating to a canary build to see if you'd fixed this but not pushed.  Unfortunately, `JsxstyleProps` doesn't appear to be exported on canary, so it would take more than just a package change to be compatible.

**Comment by meyer** [comment]
Oh dear, sorry about that. Anything Preact-related in jsxstyle@latest is going to be a bit dusty, but I’ll see if a dependency update will fix the issue. I haven’t had to patch 2.x in a while so it might take me a bit.

jsxstyle@canary shouldn’t have any issues with Preact X as far as I know. I’m using two Preact projects and one React project to test features in canary and haven’t encountered any new typing issues in quite some time.

**Comment by meyer** [comment]
In the mean time, `skipLibCheck: true` in your tsconfig should theoretically muffle the issue. Definitely not ideal though. I should have a fix out sometime tomorrow once I’ve repro’d.

**Comment by appsforartists** [comment]
Thanks!

I think I tried that, but still saw the error.  I rolled back the change.  Maybe I'll try again when the new version is out.

**Comment by meyer** [comment]
i’ve got a repro. `skipLibCheck` does indeed muffle the issue:
![Screenshot 2023-08-10 at 17 12 23](https://github.com/jsxstyle/jsxstyle/assets/13781/4b70571b-cc0a-45e0-97d1-783b744cf324)

**Comment by meyer** [comment]
A fix is out in jsxstyle@2.5.2 (fix: 2e6560e6698496ed4cc84d2b702e107a129d68f1, published: a15f0859022554d5d4cb4fd166a9b734a92a1d8f). Give it a go and let me know if you run into any more issues!

**Comment by appsforartists** [comment]
Thanks!  Looks like that fixed it!

Looks like you've been making a bunch of changes.  Is v3 written up anywhere?

**Comment by meyer** [comment]
not yet, but I’m going to to a README rewrite here in a few days
