### ISSUE TITLE
RFC: Vertical and Horizontal helpers like RN

### ISSUE THREAD

**Issue by jaredpalmer** [jsxstyle/jsxstyle#74]
`paddingVertical`, `paddingHoriztonal`, `marginVertical`, `marginHorizontal`

**Comment by meyer** [comment]
Interesting. I’ve seen this in a few other places as well, most notably Tachyons with `ph` and `pv` classes. I’m into it. Should be trivial to implement, too.

**Comment by meyer** [comment]
I’m not sure where to add this yet, but I’m still thinking about it.

**Comment by meyer** [comment]
@jaredpalmer One edge case I’m not sure how to handle is if the user specifies the shorthand prop as well as the normal prop. `jsxstyle` props are alphabetised before they’re applied, so you wouldn’t be able to rely on key order.

```jsx
<Block
  paddingVertical={4}
  paddingTop={8}
/>
```

How does React Native handle that case?

**Comment by meyer** [comment]
I’ve been thinking about this a bit and I think it would work best as a babel transform.

I’m working on making some utilities that would make writing `jsxstyle`-specific babel transforms a bit easier. The babel plugin helper in particular would visit all `JSXElement`s and call the callback only when it encounters a valid `jsxstyle` `JSXElement`.

Would look something like this:

```jsx
const {
  isStyleAttribute,
  jsxstyleVisitor,
  makeAttribute,
} require('jsxstyle-babel-utils');

module.exports = jsxstyleVisitor(path => {
  const modifiedAttributes = [];

  path.node.attributes.forEach(attr => {
    if (!isStyleAttribute(attr)) {
      modifiedAttributes.push(attr);
      return;
    }
    if (attr.name.name === 'paddingVertical') {
      modifiedAttributes.push(makeAttribute('paddingTop', attr.value));
      modifiedAttributes.push(makeAttribute('paddingBottom', attr.value));
      return;
    }
    modifiedAttributes.push(attr);
  });

  path.node.attributes = modifiedAttributes;
});
```

**Comment by meyer** [comment]
Still thinking this over but I’m going to close it for now.

**Comment by necolas** [comment]
> How does React Native handle that case?

I've documented this detail of RN, specifically https://github.com/necolas/react-native-web/blob/1776891/website/guides/style.md#how-styles-are-resolved

**Comment by meyer** [comment]
🚢 💨
