### ISSUE TITLE
Potential successor to prefix-based API

### ISSUE THREAD

**Issue by meyer** [jsxstyle/jsxstyle#90]
This is something I was thinking about a while ago that I was reminded of while I was migrating the core pieces of jsxstyle to TypeScript.

```jsx
<MediaQuery query="screen and (min-width < 1000px)" color="red">
  <Block color="blue">
    blue on big screens, red on small screens
  </Block>
</MediaQuery>

<Pseudo hover color="red">
  <Block color="blue">
    blue normally, red on hover
  </Block>
</Pseudo>
```

`MediaQuery` and `Pseudo` components generate a CSS class with the assigned styles. The render method returns a cloned `only` child with the `className` added to props.

Pros:

1. Super TypeScript-friendly.
2. Making media query components seems nice, at least in my brain. Example:

```jsx
import { MediaQuery } from 'jsxstyle';

const SmallScreen = (...props) => (
  <MediaQuery
    query="screen and your special mq"
    {...props}
  />
);

// later on...

<SmallScreen color="blue">
  <Block color="red" />
</SmallScreen>
```

Edit: this might make more sense as (sigh) a HOC:

```jsx
import { withMediaQuery } from 'jsxstyle';
const SmallScreen = withMediaQuery('screen and your special mq');
```

Cons:

1. `Pseudo` feels a bit weird and could get weirder.
2. At first glance it seems that it would not be possible to completely extract these components from runtime with `jsxstyle-loader`, even if all props were static. I think there’s a way around this though.

This could possibly be a separate package as well. Hmmm… much to think about.

**Comment by meyer** [comment]
If there’s not an elegant way to do this in JSX, we could go with either a higher-order component or object syntax on the component. I _really really really_ want to stay away from object syntax for styles if at all possible though. Styles should stay as top level props.

I think it would be possible to keep prefix syntax for pseudoclasses. `hoverColor` is nice imo. Just gets unwieldy when prefixes start stacking.

**Comment by L42y** [comment]
> I really really really want to stay away from object syntax for styles
+1 on this

Media query related logic can extract as a separate component, but I would prefer to keep using pseudoclasses’ prefix syntax.

**Comment by meyer** [comment]
it’s 2020! I’ve got some experience-based thoughts after using this prefix-based API for a while now:

1. The current media query prefix API sucks bigtime. I personally don’t use it because it sucks and it’s unintuitive. What does prop order mean? Which media query prefixed prop takes precedence?
2. Pseudoelement/pseudoclass syntax is great as it is and moving it to a dedicated "pseudo" component would really suck.
3. I don’t write nearly as many media queries as I thought I would, partly because of flexbox/CSS grid and partly because the media query prefix API sucks.

In one of my side projects I’ve been using a pretty simple media query hook. Implementation uses `window.matchMedia`, usage looks like this:

```tsx
import React from 'react';
import { Block } from 'jsxstyle';
import { useMatchMedia } from '~/hooks/useMatchMedia';

export const MyComponent = () => {
  const viewportIsSmall = useMatchMedia('screen and (max-width: 900px)');

  return (
    <Block backgroundColor={viewportIsSmall ? 'red' : 'blue'}>
      Convoluted example
    </Block>;
  );
};
```

I think it might be a nice addition to jsxstyle. Here’s my rationale:

Media query handling is done 100% in JS, but what’s super neat about this approach is that, if `useMatchMedia` comes from a _trusted source_ (i.e. `jsxstyle`), I can very easily statically analyse hook usage and completely extract the CSS:

```tsx
import React from 'react';
import { useMatchMedia } from 'jsxstyle';

export const MyComponent = () => {
  const viewportIsSmall = /*#__PURE__*/ useMatchMedia('screen and (max-width: 900px)');

  return (
    <div className="_x0">
      Convoluted example
    </div>;
  );
};
```

I need to doublecheck this theory but if I understand things correctly, the `/*#__PURE__*/` annotation here would ensure that the minifier would remove the `useMatchMedia` function call and (I think?) the jsxstyle import (TODO: `sideEffects` in `package.json` might be necessary for the import removal).

The extracted CSS would look like so:
```css
._x0 {
  display: block;
  background-color: blue;
}

@media screen and (max-width: 900px) {
  ._x0 {
    background-color: red;
  }
}
```

It’s a direct translation of intent that enables full media query support in completely statically rendered output which is, for some legacy reason that I can’t fully explain, a continuing goal of mine. It also feels a lot more intuitive (to me) than the current media query API.

In `jsxstyle-webpack-plugin` we’re already analysing the hell out of ternaries and logical expressions, so it shouldn’t be too much work to support conditionally styling things based on media queries.

Hmmmmm…

**Comment by meyer** [comment]
Here’s the current plan:

- Keep pseudo prefixes. I’ve added commonly used pseudo-prefixed styles to [the `CSSProperties` interface](https://github.com/jsxstyle/jsxstyle/blob/4b46b72/packages/jsxstyle-utils/src/types.ts#L27-L52), so the average jsxstyle user shouldn’t need to augment anything.
- Deprecate `mediaQueries` prop in favour of `useMatchMedia`. Static style extraction detailed in [the comment above](https://github.com/jsxstyle/jsxstyle/issues/90#issuecomment-606915879) is currently live in `jsxstyle@next` and will ship the next time I publish.

Barring any huge performance issues or a wildly better idea, I think this is how I’m going to proceed. I’m going to close this issue for now, but if you all have concerns/questions/comments, feel free to post ’em here.
