### ISSUE TITLE
jsxstyle 3 goal: make CSS easier to understand

### ISSUE THREAD

**Issue by meyer** [jsxstyle/jsxstyle#93]
Since we’ve now got type definitions with nice meaty comments, you can see what a CSS property does as you type if you use a compatible editor. Neat!

I think there’s more we can do here as far as education and developer experience goes. One suggestion: runtime advice.

Things we could do with this feature:

1. warn about common CSS mistakes.
2. warn about conflicting CSS properties.
3. encourage people do an old-school thing a newer way. For example: centering an element inside another element.
4. warn about [flexbugs](https://github.com/philipwalton/flexbugs).
5. warn about CSS properties that are below a certain threshold of browser support.
6. validate CSS properties at runtime.
7. encourage people to use unitless props where they’re supported (i.e., catch strings that match `/\d+px/`) and warn if there’s a unitless prop on `lineHeight` that’s above some sensible number (`lineHeight={24}` is probably a mistake).
8. warn if numeric string values are passed to unitless props (see #95).
9. warn if string values ending in `px` are passed to unitless props.

The mechanism that provides runtime advice would be minified out in production. It would exist purely to help the developer while they’re writing styles. It wouldn’t slow anything down at all… perhaps it could run in a web worker?

Automated advice can oftentimes be quite annoying, so it would most likely be an opt-in thing. I’d like it to be something that even seasoned frontend people would use though.

**Comment by chenxsan** [comment]
It would be great if jsxstyle could warn about CSS mistakes, I found myself typing wrong CSS  sometimes, like `justifyCotent`, `smfontSize`.

**Comment by meyer** [comment]
another one: `whitespace` vs `whiteSpace`
